# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/flake8
    rev: a929f12
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 3f92c8d
    hooks:
    -   id: autopep8
-   repo: https://github.com/motet-a/jinjalint
    rev: 01e0a4d
    hooks:
    -   id: jinjalint
-   repo: https://github.com/pre-commit/mirrors-csslint
    rev: ad9b0d7
    hooks:
    -   id: csslint
